openapi: 3.0.1
info:
  title: Documentación de la API de Carritos de Compra
  description: Documentación Swagger para la API de Carritos de Compra
  version: 1.0.0
paths:
  /carts/{cid}:
    get:
      summary: Obtener un carrito por su ID
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito a obtener
          schema:
            type: string
      responses:
        '200':
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
    delete:
      summary: Eliminar un carrito por su ID
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito a eliminar
          schema:
            type: string
      responses:
        '204':
          description: Carrito eliminado correctamente
        '404':
          description: Carrito no encontrado
  /carts:
    post:
      summary: Crear un nuevo carrito
      responses:
        '201':
          description: Carrito creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: Solicitud incorrecta
components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID del carrito
        user:
          type: string
          description: Usuario asociado al carrito
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                description: ID del producto
              quantity:
                type: number
                description: Cantidad del producto en el carrito